### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agmariona** [Big-Cheung/assignment0#1]
Good job. Making the AI wait a random bit of time is a good way to handicap the AI. I would say that you overcomplicate things a little too much, though. Having the AI not only wait until the ball passes the center of the screen, then still making it wait `0.05` seconds, and finally making it run through its delay time is just a little bit excessive.

Style-wise, there's a bit of an indentation mess going on here:
``` lua
else
        if ball.x > VIRTUAL_WIDTH/2 then -- Only move when the ball is on the right side
        AI_tpass = AI_tpass - dt
        AI_delay = AI_delay - dt
        if AI_delay <= 0 then
        if ball.y < player2.y then -- Move up if the ball is higher than the paddle
            if AI_tpass <= 0 then
                player2.dy = -PADDLE_SPEED
                AI_tpass = 0.05
            end
        elseif ball.y+ball.height > player2.y+player2.height then -- Move down if ball is lower than paddle
            if AI_tpass <= 0 then
                player2.dy = PADDLE_SPEED
                AI_tpass = 0.05
            end
        else 
            player2.dy = 0 --Stop moving if it is in the range of the paddle to stop paddle jittering
        end
        end
        else
            AI_delay = math.random()*0.9 -- Set delay to a little less than 1 second so that the AI doesn't win ever single time
            player2.dy = 0 --Stop movin if paddle is on opposite side of the board
        end
end
```
Every nested `if`-statement should be indented, and all `end` markers should be aligned with their corresponding `if` or `else`.

Your variable names could be a bit better as well. It is a bit unclear what exactly `AI_tpass` is supposed to do. You do leave a comment when initializing it, which helps, but I don't see how 'tpass' communicates 'variable for AI delayed movements in changing direction.'

Finally, comments on the same line as code can often be hard to read, as they'll tend to go off the screen. Just put them above the relevant line instead, adding blank lines as needed to demarcate logical chunks and maintain readability.

Let me know if you have any questions.

Alexander Mariona
agmariona@college.harvard.edu

**Comment by Big-Cheung** [comment]
Alright. Thank you! I'll improve my commenting, indentation, overall clarity and simplicity next time. Thanks for your feedback. I tried to find a way to handicap the AI but make it seem as if it was fair. The 0.05 seconds was in order to add a delay to a change in actions(such as stopping or reversing direction) to make it seem like it wasn't flawless. Thanks again for the feedback. I'll do my best to improve my code next time.
